[2024-11-10T13:51:37.492+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: banco_de_dados.insert_data manual__2024-11-10T13:51:34.467690+00:00 [queued]>
[2024-11-10T13:51:37.537+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: banco_de_dados.insert_data manual__2024-11-10T13:51:34.467690+00:00 [queued]>
[2024-11-10T13:51:37.538+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-10T13:51:37.538+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-10T13:51:37.538+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-10T13:51:37.572+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-11-10 13:51:34.467690+00:00
[2024-11-10T13:51:37.577+0000] {standard_task_runner.py:55} INFO - Started process 4118 to run task
[2024-11-10T13:51:37.582+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'banco_de_dados', 'insert_data', 'manual__2024-11-10T13:51:34.467690+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/banco_de_dados.py', '--cfg-path', '/tmp/tmpn4000w6c']
[2024-11-10T13:51:37.586+0000] {standard_task_runner.py:83} INFO - Job 184: Subtask insert_data
[2024-11-10T13:51:37.669+0000] {task_command.py:388} INFO - Running <TaskInstance: banco_de_dados.insert_data manual__2024-11-10T13:51:34.467690+00:00 [running]> on host c860a17743c7
[2024-11-10T13:51:37.721+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=banco_de_dados
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-10T13:51:34.467690+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-10T13:51:34.467690+00:00
[2024-11-10T13:51:37.721+0000] {sql.py:254} INFO - Executing: insert into teste values(1);
[2024-11-10T13:51:37.727+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-11-10T13:51:37.886+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-11-10T13:51:37.888+0000] {sql.py:375} INFO - Running statement: insert into teste values(1);, parameters: None
[2024-11-10T13:51:37.889+0000] {sql.py:384} INFO - Rows affected: 1
[2024-11-10T13:51:37.898+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=banco_de_dados, task_id=insert_data, execution_date=20241110T135134, start_date=20241110T135137, end_date=20241110T135137
[2024-11-10T13:51:37.939+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-11-10T13:51:37.964+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
