[2024-11-09T20:38:57.991+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag2.tsk1 manual__2024-11-09T20:38:56.868563+00:00 [queued]>
[2024-11-09T20:38:58.002+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag2.tsk1 manual__2024-11-09T20:38:56.868563+00:00 [queued]>
[2024-11-09T20:38:58.005+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-09T20:38:58.005+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-09T20:38:58.005+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-09T20:38:58.017+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-11-09 20:38:56.868563+00:00
[2024-11-09T20:38:58.022+0000] {standard_task_runner.py:55} INFO - Started process 6317 to run task
[2024-11-09T20:38:58.026+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag2', 'tsk1', 'manual__2024-11-09T20:38:56.868563+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag2.py', '--cfg-path', '/tmp/tmpb_v1gq2a']
[2024-11-09T20:38:58.027+0000] {standard_task_runner.py:83} INFO - Job 75: Subtask tsk1
[2024-11-09T20:38:58.095+0000] {task_command.py:388} INFO - Running <TaskInstance: trigger_dag2.tsk1 manual__2024-11-09T20:38:56.868563+00:00 [running]> on host a8ff7d7dd89a
[2024-11-09T20:38:58.147+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_dag2
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-11-09T20:38:56.868563+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-09T20:38:56.868563+00:00
[2024-11-09T20:38:58.149+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-11-09T20:38:58.149+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-11-09T20:38:58.157+0000] {subprocess.py:86} INFO - Output:
[2024-11-09T20:38:58.161+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-09T20:38:58.170+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-09T20:38:58.178+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=trigger_dag2, task_id=tsk1, execution_date=20241109T203856, start_date=20241109T203857, end_date=20241109T203858
[2024-11-09T20:38:58.188+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 75 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 6317)
[2024-11-09T20:38:58.206+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-09T20:38:58.231+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
