[2024-11-10T13:50:48.059+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: banco_de_dados.insert_data manual__2024-11-10T13:50:43.582266+00:00 [queued]>
[2024-11-10T13:50:48.088+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: banco_de_dados.insert_data manual__2024-11-10T13:50:43.582266+00:00 [queued]>
[2024-11-10T13:50:48.089+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-10T13:50:48.089+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-10T13:50:48.089+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-10T13:50:48.105+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-11-10 13:50:43.582266+00:00
[2024-11-10T13:50:48.112+0000] {standard_task_runner.py:55} INFO - Started process 4039 to run task
[2024-11-10T13:50:48.117+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'banco_de_dados', 'insert_data', 'manual__2024-11-10T13:50:43.582266+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/banco_de_dados.py', '--cfg-path', '/tmp/tmpv8n9ciat']
[2024-11-10T13:50:48.118+0000] {standard_task_runner.py:83} INFO - Job 172: Subtask insert_data
[2024-11-10T13:50:48.265+0000] {task_command.py:388} INFO - Running <TaskInstance: banco_de_dados.insert_data manual__2024-11-10T13:50:43.582266+00:00 [running]> on host c860a17743c7
[2024-11-10T13:50:48.379+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=banco_de_dados
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-10T13:50:43.582266+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-10T13:50:43.582266+00:00
[2024-11-10T13:50:48.380+0000] {sql.py:254} INFO - Executing: insert into teste values(1);
[2024-11-10T13:50:48.389+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-11-10T13:50:48.687+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-11-10T13:50:48.699+0000] {sql.py:375} INFO - Running statement: insert into teste values(1);, parameters: None
[2024-11-10T13:50:48.704+0000] {sql.py:384} INFO - Rows affected: 1
[2024-11-10T13:50:48.716+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=banco_de_dados, task_id=insert_data, execution_date=20241110T135043, start_date=20241110T135048, end_date=20241110T135048
[2024-11-10T13:50:48.752+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-11-10T13:50:48.782+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
